image: 'docker.slock.it/build-images/node:10-alpine'
stages:
  - build
  - deploy
build-pkg:
  stage: build
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
  artifacts:
    name: build-js
    paths:
      - dist/js/
push-to-registry:
  stage: deploy
  tags:
    - short-jobs
  only:
    - '/^v[0-9]*\.[0-9]*\.[0-9]*-?.*$/'
  except:
    - branches
  dependencies:
    - build-pkg
  script:
    - sh /prepare.sh
    - npm --no-git-tag-version -f version $CI_COMMIT_TAG --allow-same-version
    - npm publish

push-to-public-registry:
  stage: deploy
  tags:
    - short-jobs
  only:
    - '/^v\d+\.\d+\.\d+\-release$/'
  except:
    - branches
  dependencies:
    - build-pkg
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - CLEAN_VERSION=`echo "$CI_COMMIT_TAG"|sed s/-release//`
    - echo "using $CLEAN_VERSION as version"
    - npm --no-git-tag-version -f version $CLEAN_VERSION --allow-same-version
    - npm publish --registry=https://registry.npmjs.org

push-to-slockit-registry:
  stage: deploy
  tags:
    - short-jobs
  only:
    - '/^v[0-9]*\.[0-9]*\.[0-9]*-?.*$/'
  except:
    - branches
  dependencies:
    - build-pkg
  script:
    - sh /prepare.sh
    - npm --no-git-tag-version -f version $CI_COMMIT_TAG --allow-same-version
    - npm publish